version: '2'

services:
  pastebin:
    tty: true
    stdin_open: true
    image: pastebin:latest
    container_name: pastebin
    volumes:
      - ./config:/config
      - ./files:/files
    restart: always
    network_mode: host
    ports:
      - 192.168.10.20:80:80
 
